# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 168951600f5413fb5de53bf32dba35d83feb564eea7ce8bb539c1cd9f8aaea60e80819efc649262b97ff0133700b14ad1c00f23ff8792ea43e9cc698359c1f65

test:
  secret_key_base: 8b4c71bbd2c11000e1b586ee2fe70098066319e29466773f908a678bbc7025791442b4b126c400c1873be6762555eb3113828450841b80dced9e0e455c28706a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
